apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: learnflow
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: DEBUG
          value: "true"
