apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: learnflow
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: "1"
